#!/bin/sh -ex

SRC=/usr/local/src
WEBROOT=/var/www/foodsoft

/etc/init.d/mysql start

# get rid of sample app but store database config
mv $WEBROOT/config/database.yml /tmp/foodsoft_database.yml
rm -Rf $WEBROOT

# for each fork there is a tarball named foodsoft-<fork>-<version>.tar.gz
# the default version is called foodsoft-standard-<version>.tar.gz
for TARBALL in $SRC/foodsoft-*.tar.gz; do
    NAME=$(basename $TARBALL .tar.gz | sed -r 's|-v?[0-9]+\.[0-9]+.*$||')
    APPROOT=$(dirname $WEBROOT)/$NAME

    # extract application to webroot
    mkdir -p $APPROOT
    tar -zxf $TARBALL --strip-components 1 -C $APPROOT 
    rm -f $TARBALL

    # add database config
    cp /tmp/foodsoft_database.yml $APPROOT/config/database.yml

    # we probably have a somewhat older Ruby version; make sure Gemfile allows that
    cd $APPROOT
    sed -i 's|^\s*ruby |#ruby |' Gemfile

    # disable sharedlists in configuration, we don't use it here
    # rename key instead of commenting to make it work too when it contains children
    # (if it's a database.yml label, it may even break deployment)
    sed -ri 's|^(\s*)(shared_lists:)|\1dont_use_\2|' $APPROOT/config/app_config.yml.SAMPLE

    # do not require ssl, since we start with an untrusted certificate
    sed -ri 's|^(\s*config\.force_ssl\s*=\s*).*$|\1false|' $APPROOT/config/environments/production.rb

    # use existing MTA with sendmail
    echo 'Foodsoft::Application.configure { config.action_mailer.delivery_method = :sendmail }' >>$APPROOT/config/environments/production.rb

    # add TurnkeyLinux credit (when a footer is available)
    sed -ri 's|^((.*)\.pull-right)|\1= raw ("\&nbsp;on " + link_to("Turnkey Linux", "http://www.turnkeylinux.org"))\n\1|' $APPROOT/app/views/layouts/_footer.html.haml 2>/dev/null || true

    # install dependencies
    [ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY
    bundle install --without test development
    bundle exec rake foodsoft:setup:stock_config RAILS_ENV=production
    unset HTTP_PROXY

    # there is only one default application, setup database for that
    if [ $NAME = foodsoft-standard ]; then
        bundle exec rake db:setup railties:install:migrations db:migrate RAILS_ENV=production
        ln -s $NAME $WEBROOT
    fi

    bundle exec rake assets:precompile RAILS_ENV=production

    # configure permissions
    mkdir -p $APPROOT/tmp/pids
    chown -R root:www-data $APPROOT
    chown -R www-data:www-data $APPROOT/tmp
    chown -R www-data:www-data $APPROOT/log

done

# start foodsoft worker by default
update-rc.d foodsoft-workers defaults

# cleanup
rm -f /tmp/foodsoft_database.yml
/etc/init.d/mysql stop

