#!/bin/bash -e
# propagate rails secret updates to all installed versions
# (must happen after 20regen-rails-secrets)

. /etc/default/inithooks

WEBROOT=/var/www/foodsoft
for DIR in /var/www/foodsoft-*; do
    if [ ! $DIR -ef $WEBROOT ]; then
      # Now when a Rails 3.2 secret is not found, make sure to set that.
      # (Rails 4 works with both, but Rails 3.2 fails without a secret_token.)
      if ! grep -vq 'Application\.config\.secret_token' $WEBROOT/config/initializers/secret_token.rb; then
          echo "Foodsoft::Application.config.secret_token = Foodsoft::Application.config.secret_key_base" \
                 >>$WEBROOT/config/initializers/secret_token.rb
      fi
      # Copy updates to all versions
      cp $WEBROOT/config/database.yml $DIR/config/database.yml
      cp $WEBROOT/config/initializers/secret_token.rb $DIR/config/initializers/secret_token.rb
    fi
done
