#!/bin/bash -e
# propagate rails secret updates to all installed versions
# (must happen after 20regen-rails-secrets)

. /etc/default/inithooks

WEBROOT=/var/www/foodsoft
for DIR in /var/www/foodsoft-*; do
    if [ ! $DIR -ef $WEBROOT ]; then
      cp $WEBROOT/config/database.yml $DIR/config/database.yml
      cp $WEBROOT/config/initializers/secret_token.rb $DIR/config/initializers/secret_token.rb
    fi
done
